// @file
// This file is part of SeisSol.
// 
// @author Alexander Breuer (breuera AT in.tum.de, http://www5.in.tum.de/wiki/index.php/Dipl.-Math._Alexander_Breuer)
// @author Alexander Heinecke (heinecke AT in.tum.de, http://www5.in.tum.de/wiki/index.php/Alexander_Heinecke,_M.Sc.,_M.Sc._with_honors)
// 
// @date 2012-11-29 18:54:13.117711
// 
// @section LICENSE
// This software was developed at Technische Universitaet Muenchen, who is the owner of the software.
// 
// According to good scientific practice, publications on results achieved in whole or in part due to this software should cite at least one paper or referring to an URL presenting the this software software.
// 
// The owner wishes to make the software available to all users to use, reproduce, modify, distribute and redistribute also for commercial purposes under the following conditions of the original BSD license. Linking this software module statically or dynamically with other modules is making a combined work based on this software. Thus, the terms and conditions of this license cover the whole combination. As a special exception, the copyright holders of this software give you permission to link it with independent modules or to instantiate templates and macros from this software's source files to produce an executable, regardless of the license terms of these independent modules, and to copy and distribute the resulting executable under terms of your choice, provided that you also meet, for each linked independent module, the terms and conditions of this license of that module.
// 
// Copyright (c) 2012
// Technische Universitaet Muenchen
// Department of Informatics
// Chair of Scientific Computing
// http://www5.in.tum.de/
// 
// All rights reserved.
// 
// Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
// 
// Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
// Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
// All advertising materials mentioning features or use of this software must display the following acknowledgement: This product includes software developed by the Technische Universitaet Muenchen (TUM), Germany, and its contributors.
// Neither the name of the Technische Universitaet Muenchen, Munich, Germany nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
// 
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. 
//
// @section DESCRIPTION
// 
// Defines matrix sizes in the preprocessing phase.
//   Remark: This file was generated. It should not be modified by hand.
// 
#if NUMBEROFBASISFUNCTIONS == 4
#define FM1_NUMBEROFNONZEROS 6
#endif 

#if NUMBEROFBASISFUNCTIONS == 10
#define FM1_NUMBEROFNONZEROS 20
#endif 

#if NUMBEROFBASISFUNCTIONS == 20
#define FM1_NUMBEROFNONZEROS 50
#endif 

#if NUMBEROFBASISFUNCTIONS == 35
#define FM1_NUMBEROFNONZEROS 105
#endif 

#if NUMBEROFBASISFUNCTIONS == 56
#define FM1_NUMBEROFNONZEROS 196
#endif 

#if NUMBEROFBASISFUNCTIONS == 84
#define FM1_NUMBEROFNONZEROS 336
#endif 

#if NUMBEROFBASISFUNCTIONS == 4
#define FM2_NUMBEROFNONZEROS 8
#endif 

#if NUMBEROFBASISFUNCTIONS == 10
#define FM2_NUMBEROFNONZEROS 34
#endif 

#if NUMBEROFBASISFUNCTIONS == 20
#define FM2_NUMBEROFNONZEROS 104
#endif 

#if NUMBEROFBASISFUNCTIONS == 35
#define FM2_NUMBEROFNONZEROS 259
#endif 

#if NUMBEROFBASISFUNCTIONS == 56
#define FM2_NUMBEROFNONZEROS 560
#endif 

#if NUMBEROFBASISFUNCTIONS == 84
#define FM2_NUMBEROFNONZEROS 1092
#endif 

#if NUMBEROFBASISFUNCTIONS == 4
#define FM3_NUMBEROFNONZEROS 10
#endif 

#if NUMBEROFBASISFUNCTIONS == 10
#define FM3_NUMBEROFNONZEROS 54
#endif 

#if NUMBEROFBASISFUNCTIONS == 20
#define FM3_NUMBEROFNONZEROS 204
#endif 

#if NUMBEROFBASISFUNCTIONS == 35
#define FM3_NUMBEROFNONZEROS 609
#endif 

#if NUMBEROFBASISFUNCTIONS == 56
#define FM3_NUMBEROFNONZEROS 1540
#endif 

#if NUMBEROFBASISFUNCTIONS == 84
#define FM3_NUMBEROFNONZEROS 3444
#endif 

#if NUMBEROFBASISFUNCTIONS == 4
#define FM4_NUMBEROFNONZEROS 10
#endif 

#if NUMBEROFBASISFUNCTIONS == 10
#define FM4_NUMBEROFNONZEROS 54
#endif 

#if NUMBEROFBASISFUNCTIONS == 20
#define FM4_NUMBEROFNONZEROS 204
#endif 

#if NUMBEROFBASISFUNCTIONS == 35
#define FM4_NUMBEROFNONZEROS 609
#endif 

#if NUMBEROFBASISFUNCTIONS == 56
#define FM4_NUMBEROFNONZEROS 1540
#endif 

#if NUMBEROFBASISFUNCTIONS == 84
#define FM4_NUMBEROFNONZEROS 3444
#endif 

#if NUMBEROFBASISFUNCTIONS == 4
#define FP111_NUMBEROFNONZEROS 8
#endif 

#if NUMBEROFBASISFUNCTIONS == 10
#define FP111_NUMBEROFNONZEROS 34
#endif 

#if NUMBEROFBASISFUNCTIONS == 20
#define FP111_NUMBEROFNONZEROS 104
#endif 

#if NUMBEROFBASISFUNCTIONS == 35
#define FP111_NUMBEROFNONZEROS 257
#endif 

#if NUMBEROFBASISFUNCTIONS == 56
#define FP111_NUMBEROFNONZEROS 552
#endif 

#if NUMBEROFBASISFUNCTIONS == 84
#define FP111_NUMBEROFNONZEROS 1074
#endif 

#if NUMBEROFBASISFUNCTIONS == 4
#define FP112_NUMBEROFNONZEROS 8
#endif 

#if NUMBEROFBASISFUNCTIONS == 10
#define FP112_NUMBEROFNONZEROS 34
#endif 

#if NUMBEROFBASISFUNCTIONS == 20
#define FP112_NUMBEROFNONZEROS 104
#endif 

#if NUMBEROFBASISFUNCTIONS == 35
#define FP112_NUMBEROFNONZEROS 257
#endif 

#if NUMBEROFBASISFUNCTIONS == 56
#define FP112_NUMBEROFNONZEROS 552
#endif 

#if NUMBEROFBASISFUNCTIONS == 84
#define FP112_NUMBEROFNONZEROS 1074
#endif 

#if NUMBEROFBASISFUNCTIONS == 4
#define FP113_NUMBEROFNONZEROS 6
#endif 

#if NUMBEROFBASISFUNCTIONS == 10
#define FP113_NUMBEROFNONZEROS 20
#endif 

#if NUMBEROFBASISFUNCTIONS == 20
#define FP113_NUMBEROFNONZEROS 50
#endif 

#if NUMBEROFBASISFUNCTIONS == 35
#define FP113_NUMBEROFNONZEROS 105
#endif 

#if NUMBEROFBASISFUNCTIONS == 56
#define FP113_NUMBEROFNONZEROS 196
#endif 

#if NUMBEROFBASISFUNCTIONS == 84
#define FP113_NUMBEROFNONZEROS 336
#endif 

#if NUMBEROFBASISFUNCTIONS == 4
#define FP121_NUMBEROFNONZEROS 9
#endif 

#if NUMBEROFBASISFUNCTIONS == 10
#define FP121_NUMBEROFNONZEROS 40
#endif 

#if NUMBEROFBASISFUNCTIONS == 20
#define FP121_NUMBEROFNONZEROS 125
#endif 

#if NUMBEROFBASISFUNCTIONS == 35
#define FP121_NUMBEROFNONZEROS 315
#endif 

#if NUMBEROFBASISFUNCTIONS == 56
#define FP121_NUMBEROFNONZEROS 686
#endif 

#if NUMBEROFBASISFUNCTIONS == 84
#define FP121_NUMBEROFNONZEROS 1344
#endif 

#if NUMBEROFBASISFUNCTIONS == 4
#define FP122_NUMBEROFNONZEROS 12
#endif 

#if NUMBEROFBASISFUNCTIONS == 10
#define FP122_NUMBEROFNONZEROS 68
#endif 

#if NUMBEROFBASISFUNCTIONS == 20
#define FP122_NUMBEROFNONZEROS 260
#endif 

#if NUMBEROFBASISFUNCTIONS == 35
#define FP122_NUMBEROFNONZEROS 771
#endif 

#if NUMBEROFBASISFUNCTIONS == 56
#define FP122_NUMBEROFNONZEROS 1932
#endif 

#if NUMBEROFBASISFUNCTIONS == 84
#define FP122_NUMBEROFNONZEROS 4296
#endif 

#if NUMBEROFBASISFUNCTIONS == 4
#define FP123_NUMBEROFNONZEROS 12
#endif 

#if NUMBEROFBASISFUNCTIONS == 10
#define FP123_NUMBEROFNONZEROS 68
#endif 

#if NUMBEROFBASISFUNCTIONS == 20
#define FP123_NUMBEROFNONZEROS 260
#endif 

#if NUMBEROFBASISFUNCTIONS == 35
#define FP123_NUMBEROFNONZEROS 771
#endif 

#if NUMBEROFBASISFUNCTIONS == 56
#define FP123_NUMBEROFNONZEROS 1932
#endif 

#if NUMBEROFBASISFUNCTIONS == 84
#define FP123_NUMBEROFNONZEROS 4296
#endif 

#if NUMBEROFBASISFUNCTIONS == 4
#define FP131_NUMBEROFNONZEROS 14
#endif 

#if NUMBEROFBASISFUNCTIONS == 10
#define FP131_NUMBEROFNONZEROS 81
#endif 

#if NUMBEROFBASISFUNCTIONS == 20
#define FP131_NUMBEROFNONZEROS 320
#endif 

#if NUMBEROFBASISFUNCTIONS == 35
#define FP131_NUMBEROFNONZEROS 979
#endif 

#if NUMBEROFBASISFUNCTIONS == 56
#define FP131_NUMBEROFNONZEROS 2518
#endif 

#if NUMBEROFBASISFUNCTIONS == 84
#define FP131_NUMBEROFNONZEROS 5626
#endif 

#if NUMBEROFBASISFUNCTIONS == 4
#define FP132_NUMBEROFNONZEROS 13
#endif 

#if NUMBEROFBASISFUNCTIONS == 10
#define FP132_NUMBEROFNONZEROS 76
#endif 

#if NUMBEROFBASISFUNCTIONS == 20
#define FP132_NUMBEROFNONZEROS 286
#endif 

#if NUMBEROFBASISFUNCTIONS == 35
#define FP132_NUMBEROFNONZEROS 860
#endif 

#if NUMBEROFBASISFUNCTIONS == 56
#define FP132_NUMBEROFNONZEROS 2214
#endif 

#if NUMBEROFBASISFUNCTIONS == 84
#define FP132_NUMBEROFNONZEROS 4989
#endif 

#if NUMBEROFBASISFUNCTIONS == 4
#define FP133_NUMBEROFNONZEROS 13
#endif 

#if NUMBEROFBASISFUNCTIONS == 10
#define FP133_NUMBEROFNONZEROS 76
#endif 

#if NUMBEROFBASISFUNCTIONS == 20
#define FP133_NUMBEROFNONZEROS 295
#endif 

#if NUMBEROFBASISFUNCTIONS == 35
#define FP133_NUMBEROFNONZEROS 876
#endif 

#if NUMBEROFBASISFUNCTIONS == 56
#define FP133_NUMBEROFNONZEROS 2214
#endif 

#if NUMBEROFBASISFUNCTIONS == 84
#define FP133_NUMBEROFNONZEROS 4955
#endif 

#if NUMBEROFBASISFUNCTIONS == 4
#define FP141_NUMBEROFNONZEROS 13
#endif 

#if NUMBEROFBASISFUNCTIONS == 10
#define FP141_NUMBEROFNONZEROS 76
#endif 

#if NUMBEROFBASISFUNCTIONS == 20
#define FP141_NUMBEROFNONZEROS 295
#endif 

#if NUMBEROFBASISFUNCTIONS == 35
#define FP141_NUMBEROFNONZEROS 876
#endif 

#if NUMBEROFBASISFUNCTIONS == 56
#define FP141_NUMBEROFNONZEROS 2214
#endif 

#if NUMBEROFBASISFUNCTIONS == 84
#define FP141_NUMBEROFNONZEROS 4955
#endif 

#if NUMBEROFBASISFUNCTIONS == 4
#define FP142_NUMBEROFNONZEROS 13
#endif 

#if NUMBEROFBASISFUNCTIONS == 10
#define FP142_NUMBEROFNONZEROS 76
#endif 

#if NUMBEROFBASISFUNCTIONS == 20
#define FP142_NUMBEROFNONZEROS 286
#endif 

#if NUMBEROFBASISFUNCTIONS == 35
#define FP142_NUMBEROFNONZEROS 860
#endif 

#if NUMBEROFBASISFUNCTIONS == 56
#define FP142_NUMBEROFNONZEROS 2214
#endif 

#if NUMBEROFBASISFUNCTIONS == 84
#define FP142_NUMBEROFNONZEROS 4989
#endif 

#if NUMBEROFBASISFUNCTIONS == 4
#define FP143_NUMBEROFNONZEROS 14
#endif 

#if NUMBEROFBASISFUNCTIONS == 10
#define FP143_NUMBEROFNONZEROS 81
#endif 

#if NUMBEROFBASISFUNCTIONS == 20
#define FP143_NUMBEROFNONZEROS 320
#endif 

#if NUMBEROFBASISFUNCTIONS == 35
#define FP143_NUMBEROFNONZEROS 979
#endif 

#if NUMBEROFBASISFUNCTIONS == 56
#define FP143_NUMBEROFNONZEROS 2518
#endif 

#if NUMBEROFBASISFUNCTIONS == 84
#define FP143_NUMBEROFNONZEROS 5626
#endif 

#if NUMBEROFBASISFUNCTIONS == 4
#define FP211_NUMBEROFNONZEROS 9
#endif 

#if NUMBEROFBASISFUNCTIONS == 10
#define FP211_NUMBEROFNONZEROS 40
#endif 

#if NUMBEROFBASISFUNCTIONS == 20
#define FP211_NUMBEROFNONZEROS 125
#endif 

#if NUMBEROFBASISFUNCTIONS == 35
#define FP211_NUMBEROFNONZEROS 315
#endif 

#if NUMBEROFBASISFUNCTIONS == 56
#define FP211_NUMBEROFNONZEROS 686
#endif 

#if NUMBEROFBASISFUNCTIONS == 84
#define FP211_NUMBEROFNONZEROS 1344
#endif 

#if NUMBEROFBASISFUNCTIONS == 4
#define FP212_NUMBEROFNONZEROS 12
#endif 

#if NUMBEROFBASISFUNCTIONS == 10
#define FP212_NUMBEROFNONZEROS 68
#endif 

#if NUMBEROFBASISFUNCTIONS == 20
#define FP212_NUMBEROFNONZEROS 260
#endif 

#if NUMBEROFBASISFUNCTIONS == 35
#define FP212_NUMBEROFNONZEROS 771
#endif 

#if NUMBEROFBASISFUNCTIONS == 56
#define FP212_NUMBEROFNONZEROS 1932
#endif 

#if NUMBEROFBASISFUNCTIONS == 84
#define FP212_NUMBEROFNONZEROS 4296
#endif 

#if NUMBEROFBASISFUNCTIONS == 4
#define FP213_NUMBEROFNONZEROS 12
#endif 

#if NUMBEROFBASISFUNCTIONS == 10
#define FP213_NUMBEROFNONZEROS 68
#endif 

#if NUMBEROFBASISFUNCTIONS == 20
#define FP213_NUMBEROFNONZEROS 260
#endif 

#if NUMBEROFBASISFUNCTIONS == 35
#define FP213_NUMBEROFNONZEROS 771
#endif 

#if NUMBEROFBASISFUNCTIONS == 56
#define FP213_NUMBEROFNONZEROS 1932
#endif 

#if NUMBEROFBASISFUNCTIONS == 84
#define FP213_NUMBEROFNONZEROS 4296
#endif 

#if NUMBEROFBASISFUNCTIONS == 4
#define FP221_NUMBEROFNONZEROS 14
#endif 

#if NUMBEROFBASISFUNCTIONS == 10
#define FP221_NUMBEROFNONZEROS 84
#endif 

#if NUMBEROFBASISFUNCTIONS == 20
#define FP221_NUMBEROFNONZEROS 338
#endif 

#if NUMBEROFBASISFUNCTIONS == 35
#define FP221_NUMBEROFNONZEROS 1045
#endif 

#if NUMBEROFBASISFUNCTIONS == 56
#define FP221_NUMBEROFNONZEROS 2698
#endif 

#if NUMBEROFBASISFUNCTIONS == 84
#define FP221_NUMBEROFNONZEROS 6090
#endif 

#if NUMBEROFBASISFUNCTIONS == 4
#define FP222_NUMBEROFNONZEROS 8
#endif 

#if NUMBEROFBASISFUNCTIONS == 10
#define FP222_NUMBEROFNONZEROS 34
#endif 

#if NUMBEROFBASISFUNCTIONS == 20
#define FP222_NUMBEROFNONZEROS 104
#endif 

#if NUMBEROFBASISFUNCTIONS == 35
#define FP222_NUMBEROFNONZEROS 259
#endif 

#if NUMBEROFBASISFUNCTIONS == 56
#define FP222_NUMBEROFNONZEROS 560
#endif 

#if NUMBEROFBASISFUNCTIONS == 84
#define FP222_NUMBEROFNONZEROS 1092
#endif 

#if NUMBEROFBASISFUNCTIONS == 4
#define FP223_NUMBEROFNONZEROS 14
#endif 

#if NUMBEROFBASISFUNCTIONS == 10
#define FP223_NUMBEROFNONZEROS 84
#endif 

#if NUMBEROFBASISFUNCTIONS == 20
#define FP223_NUMBEROFNONZEROS 338
#endif 

#if NUMBEROFBASISFUNCTIONS == 35
#define FP223_NUMBEROFNONZEROS 1045
#endif 

#if NUMBEROFBASISFUNCTIONS == 56
#define FP223_NUMBEROFNONZEROS 2698
#endif 

#if NUMBEROFBASISFUNCTIONS == 84
#define FP223_NUMBEROFNONZEROS 6090
#endif 

#if NUMBEROFBASISFUNCTIONS == 4
#define FP231_NUMBEROFNONZEROS 11
#endif 

#if NUMBEROFBASISFUNCTIONS == 10
#define FP231_NUMBEROFNONZEROS 61
#endif 

#if NUMBEROFBASISFUNCTIONS == 20
#define FP231_NUMBEROFNONZEROS 232
#endif 

#if NUMBEROFBASISFUNCTIONS == 35
#define FP231_NUMBEROFNONZEROS 684
#endif 

#if NUMBEROFBASISFUNCTIONS == 56
#define FP231_NUMBEROFNONZEROS 1722
#endif 

#if NUMBEROFBASISFUNCTIONS == 84
#define FP231_NUMBEROFNONZEROS 3845
#endif 

#if NUMBEROFBASISFUNCTIONS == 4
#define FP232_NUMBEROFNONZEROS 14
#endif 

#if NUMBEROFBASISFUNCTIONS == 10
#define FP232_NUMBEROFNONZEROS 84
#endif 

#if NUMBEROFBASISFUNCTIONS == 20
#define FP232_NUMBEROFNONZEROS 340
#endif 

#if NUMBEROFBASISFUNCTIONS == 35
#define FP232_NUMBEROFNONZEROS 1039
#endif 

#if NUMBEROFBASISFUNCTIONS == 56
#define FP232_NUMBEROFNONZEROS 2686
#endif 

#if NUMBEROFBASISFUNCTIONS == 84
#define FP232_NUMBEROFNONZEROS 6069
#endif 

#if NUMBEROFBASISFUNCTIONS == 4
#define FP233_NUMBEROFNONZEROS 14
#endif 

#if NUMBEROFBASISFUNCTIONS == 10
#define FP233_NUMBEROFNONZEROS 84
#endif 

#if NUMBEROFBASISFUNCTIONS == 20
#define FP233_NUMBEROFNONZEROS 325
#endif 

#if NUMBEROFBASISFUNCTIONS == 35
#define FP233_NUMBEROFNONZEROS 980
#endif 

#if NUMBEROFBASISFUNCTIONS == 56
#define FP233_NUMBEROFNONZEROS 2509
#endif 

#if NUMBEROFBASISFUNCTIONS == 84
#define FP233_NUMBEROFNONZEROS 5658
#endif 

#if NUMBEROFBASISFUNCTIONS == 4
#define FP241_NUMBEROFNONZEROS 14
#endif 

#if NUMBEROFBASISFUNCTIONS == 10
#define FP241_NUMBEROFNONZEROS 84
#endif 

#if NUMBEROFBASISFUNCTIONS == 20
#define FP241_NUMBEROFNONZEROS 340
#endif 

#if NUMBEROFBASISFUNCTIONS == 35
#define FP241_NUMBEROFNONZEROS 1039
#endif 

#if NUMBEROFBASISFUNCTIONS == 56
#define FP241_NUMBEROFNONZEROS 2686
#endif 

#if NUMBEROFBASISFUNCTIONS == 84
#define FP241_NUMBEROFNONZEROS 6069
#endif 

#if NUMBEROFBASISFUNCTIONS == 4
#define FP242_NUMBEROFNONZEROS 11
#endif 

#if NUMBEROFBASISFUNCTIONS == 10
#define FP242_NUMBEROFNONZEROS 61
#endif 

#if NUMBEROFBASISFUNCTIONS == 20
#define FP242_NUMBEROFNONZEROS 232
#endif 

#if NUMBEROFBASISFUNCTIONS == 35
#define FP242_NUMBEROFNONZEROS 684
#endif 

#if NUMBEROFBASISFUNCTIONS == 56
#define FP242_NUMBEROFNONZEROS 1722
#endif 

#if NUMBEROFBASISFUNCTIONS == 84
#define FP242_NUMBEROFNONZEROS 3845
#endif 

#if NUMBEROFBASISFUNCTIONS == 4
#define FP243_NUMBEROFNONZEROS 14
#endif 

#if NUMBEROFBASISFUNCTIONS == 10
#define FP243_NUMBEROFNONZEROS 84
#endif 

#if NUMBEROFBASISFUNCTIONS == 20
#define FP243_NUMBEROFNONZEROS 325
#endif 

#if NUMBEROFBASISFUNCTIONS == 35
#define FP243_NUMBEROFNONZEROS 980
#endif 

#if NUMBEROFBASISFUNCTIONS == 56
#define FP243_NUMBEROFNONZEROS 2509
#endif 

#if NUMBEROFBASISFUNCTIONS == 84
#define FP243_NUMBEROFNONZEROS 5658
#endif 

#if NUMBEROFBASISFUNCTIONS == 4
#define FP311_NUMBEROFNONZEROS 14
#endif 

#if NUMBEROFBASISFUNCTIONS == 10
#define FP311_NUMBEROFNONZEROS 81
#endif 

#if NUMBEROFBASISFUNCTIONS == 20
#define FP311_NUMBEROFNONZEROS 320
#endif 

#if NUMBEROFBASISFUNCTIONS == 35
#define FP311_NUMBEROFNONZEROS 979
#endif 

#if NUMBEROFBASISFUNCTIONS == 56
#define FP311_NUMBEROFNONZEROS 2518
#endif 

#if NUMBEROFBASISFUNCTIONS == 84
#define FP311_NUMBEROFNONZEROS 5626
#endif 

#if NUMBEROFBASISFUNCTIONS == 4
#define FP312_NUMBEROFNONZEROS 13
#endif 

#if NUMBEROFBASISFUNCTIONS == 10
#define FP312_NUMBEROFNONZEROS 76
#endif 

#if NUMBEROFBASISFUNCTIONS == 20
#define FP312_NUMBEROFNONZEROS 286
#endif 

#if NUMBEROFBASISFUNCTIONS == 35
#define FP312_NUMBEROFNONZEROS 860
#endif 

#if NUMBEROFBASISFUNCTIONS == 56
#define FP312_NUMBEROFNONZEROS 2214
#endif 

#if NUMBEROFBASISFUNCTIONS == 84
#define FP312_NUMBEROFNONZEROS 4989
#endif 

#if NUMBEROFBASISFUNCTIONS == 4
#define FP313_NUMBEROFNONZEROS 13
#endif 

#if NUMBEROFBASISFUNCTIONS == 10
#define FP313_NUMBEROFNONZEROS 76
#endif 

#if NUMBEROFBASISFUNCTIONS == 20
#define FP313_NUMBEROFNONZEROS 295
#endif 

#if NUMBEROFBASISFUNCTIONS == 35
#define FP313_NUMBEROFNONZEROS 876
#endif 

#if NUMBEROFBASISFUNCTIONS == 56
#define FP313_NUMBEROFNONZEROS 2214
#endif 

#if NUMBEROFBASISFUNCTIONS == 84
#define FP313_NUMBEROFNONZEROS 4955
#endif 

#if NUMBEROFBASISFUNCTIONS == 4
#define FP321_NUMBEROFNONZEROS 11
#endif 

#if NUMBEROFBASISFUNCTIONS == 10
#define FP321_NUMBEROFNONZEROS 61
#endif 

#if NUMBEROFBASISFUNCTIONS == 20
#define FP321_NUMBEROFNONZEROS 232
#endif 

#if NUMBEROFBASISFUNCTIONS == 35
#define FP321_NUMBEROFNONZEROS 684
#endif 

#if NUMBEROFBASISFUNCTIONS == 56
#define FP321_NUMBEROFNONZEROS 1722
#endif 

#if NUMBEROFBASISFUNCTIONS == 84
#define FP321_NUMBEROFNONZEROS 3845
#endif 

#if NUMBEROFBASISFUNCTIONS == 4
#define FP322_NUMBEROFNONZEROS 14
#endif 

#if NUMBEROFBASISFUNCTIONS == 10
#define FP322_NUMBEROFNONZEROS 84
#endif 

#if NUMBEROFBASISFUNCTIONS == 20
#define FP322_NUMBEROFNONZEROS 340
#endif 

#if NUMBEROFBASISFUNCTIONS == 35
#define FP322_NUMBEROFNONZEROS 1039
#endif 

#if NUMBEROFBASISFUNCTIONS == 56
#define FP322_NUMBEROFNONZEROS 2686
#endif 

#if NUMBEROFBASISFUNCTIONS == 84
#define FP322_NUMBEROFNONZEROS 6069
#endif 

#if NUMBEROFBASISFUNCTIONS == 4
#define FP323_NUMBEROFNONZEROS 14
#endif 

#if NUMBEROFBASISFUNCTIONS == 10
#define FP323_NUMBEROFNONZEROS 84
#endif 

#if NUMBEROFBASISFUNCTIONS == 20
#define FP323_NUMBEROFNONZEROS 325
#endif 

#if NUMBEROFBASISFUNCTIONS == 35
#define FP323_NUMBEROFNONZEROS 980
#endif 

#if NUMBEROFBASISFUNCTIONS == 56
#define FP323_NUMBEROFNONZEROS 2509
#endif 

#if NUMBEROFBASISFUNCTIONS == 84
#define FP323_NUMBEROFNONZEROS 5658
#endif 

#if NUMBEROFBASISFUNCTIONS == 4
#define FP331_NUMBEROFNONZEROS 12
#endif 

#if NUMBEROFBASISFUNCTIONS == 10
#define FP331_NUMBEROFNONZEROS 68
#endif 

#if NUMBEROFBASISFUNCTIONS == 20
#define FP331_NUMBEROFNONZEROS 258
#endif 

#if NUMBEROFBASISFUNCTIONS == 35
#define FP331_NUMBEROFNONZEROS 773
#endif 

#if NUMBEROFBASISFUNCTIONS == 56
#define FP331_NUMBEROFNONZEROS 1946
#endif 

#if NUMBEROFBASISFUNCTIONS == 84
#define FP331_NUMBEROFNONZEROS 4342
#endif 

#if NUMBEROFBASISFUNCTIONS == 4
#define FP332_NUMBEROFNONZEROS 16
#endif 

#if NUMBEROFBASISFUNCTIONS == 10
#define FP332_NUMBEROFNONZEROS 98
#endif 

#if NUMBEROFBASISFUNCTIONS == 20
#define FP332_NUMBEROFNONZEROS 394
#endif 

#if NUMBEROFBASISFUNCTIONS == 35
#define FP332_NUMBEROFNONZEROS 1213
#endif 

#if NUMBEROFBASISFUNCTIONS == 56
#define FP332_NUMBEROFNONZEROS 3124
#endif 

#if NUMBEROFBASISFUNCTIONS == 84
#define FP332_NUMBEROFNONZEROS 7022
#endif 

#if NUMBEROFBASISFUNCTIONS == 4
#define FP333_NUMBEROFNONZEROS 12
#endif 

#if NUMBEROFBASISFUNCTIONS == 10
#define FP333_NUMBEROFNONZEROS 70
#endif 

#if NUMBEROFBASISFUNCTIONS == 20
#define FP333_NUMBEROFNONZEROS 274
#endif 

#if NUMBEROFBASISFUNCTIONS == 35
#define FP333_NUMBEROFNONZEROS 831
#endif 

#if NUMBEROFBASISFUNCTIONS == 56
#define FP333_NUMBEROFNONZEROS 2120
#endif 

#if NUMBEROFBASISFUNCTIONS == 84
#define FP333_NUMBEROFNONZEROS 4766
#endif 

#if NUMBEROFBASISFUNCTIONS == 4
#define FP341_NUMBEROFNONZEROS 10
#endif 

#if NUMBEROFBASISFUNCTIONS == 10
#define FP341_NUMBEROFNONZEROS 54
#endif 

#if NUMBEROFBASISFUNCTIONS == 20
#define FP341_NUMBEROFNONZEROS 204
#endif 

#if NUMBEROFBASISFUNCTIONS == 35
#define FP341_NUMBEROFNONZEROS 609
#endif 

#if NUMBEROFBASISFUNCTIONS == 56
#define FP341_NUMBEROFNONZEROS 1540
#endif 

#if NUMBEROFBASISFUNCTIONS == 84
#define FP341_NUMBEROFNONZEROS 3444
#endif 

#if NUMBEROFBASISFUNCTIONS == 4
#define FP342_NUMBEROFNONZEROS 15
#endif 

#if NUMBEROFBASISFUNCTIONS == 10
#define FP342_NUMBEROFNONZEROS 93
#endif 

#if NUMBEROFBASISFUNCTIONS == 20
#define FP342_NUMBEROFNONZEROS 371
#endif 

#if NUMBEROFBASISFUNCTIONS == 35
#define FP342_NUMBEROFNONZEROS 1131
#endif 

#if NUMBEROFBASISFUNCTIONS == 56
#define FP342_NUMBEROFNONZEROS 2905
#endif 

#if NUMBEROFBASISFUNCTIONS == 84
#define FP342_NUMBEROFNONZEROS 6556
#endif 

#if NUMBEROFBASISFUNCTIONS == 4
#define FP343_NUMBEROFNONZEROS 15
#endif 

#if NUMBEROFBASISFUNCTIONS == 10
#define FP343_NUMBEROFNONZEROS 93
#endif 

#if NUMBEROFBASISFUNCTIONS == 20
#define FP343_NUMBEROFNONZEROS 371
#endif 

#if NUMBEROFBASISFUNCTIONS == 35
#define FP343_NUMBEROFNONZEROS 1131
#endif 

#if NUMBEROFBASISFUNCTIONS == 56
#define FP343_NUMBEROFNONZEROS 2905
#endif 

#if NUMBEROFBASISFUNCTIONS == 84
#define FP343_NUMBEROFNONZEROS 6556
#endif 

#if NUMBEROFBASISFUNCTIONS == 4
#define FP411_NUMBEROFNONZEROS 13
#endif 

#if NUMBEROFBASISFUNCTIONS == 10
#define FP411_NUMBEROFNONZEROS 76
#endif 

#if NUMBEROFBASISFUNCTIONS == 20
#define FP411_NUMBEROFNONZEROS 295
#endif 

#if NUMBEROFBASISFUNCTIONS == 35
#define FP411_NUMBEROFNONZEROS 876
#endif 

#if NUMBEROFBASISFUNCTIONS == 56
#define FP411_NUMBEROFNONZEROS 2214
#endif 

#if NUMBEROFBASISFUNCTIONS == 84
#define FP411_NUMBEROFNONZEROS 4955
#endif 

#if NUMBEROFBASISFUNCTIONS == 4
#define FP412_NUMBEROFNONZEROS 13
#endif 

#if NUMBEROFBASISFUNCTIONS == 10
#define FP412_NUMBEROFNONZEROS 76
#endif 

#if NUMBEROFBASISFUNCTIONS == 20
#define FP412_NUMBEROFNONZEROS 286
#endif 

#if NUMBEROFBASISFUNCTIONS == 35
#define FP412_NUMBEROFNONZEROS 860
#endif 

#if NUMBEROFBASISFUNCTIONS == 56
#define FP412_NUMBEROFNONZEROS 2214
#endif 

#if NUMBEROFBASISFUNCTIONS == 84
#define FP412_NUMBEROFNONZEROS 4989
#endif 

#if NUMBEROFBASISFUNCTIONS == 4
#define FP413_NUMBEROFNONZEROS 14
#endif 

#if NUMBEROFBASISFUNCTIONS == 10
#define FP413_NUMBEROFNONZEROS 81
#endif 

#if NUMBEROFBASISFUNCTIONS == 20
#define FP413_NUMBEROFNONZEROS 320
#endif 

#if NUMBEROFBASISFUNCTIONS == 35
#define FP413_NUMBEROFNONZEROS 979
#endif 

#if NUMBEROFBASISFUNCTIONS == 56
#define FP413_NUMBEROFNONZEROS 2518
#endif 

#if NUMBEROFBASISFUNCTIONS == 84
#define FP413_NUMBEROFNONZEROS 5626
#endif 

#if NUMBEROFBASISFUNCTIONS == 4
#define FP421_NUMBEROFNONZEROS 14
#endif 

#if NUMBEROFBASISFUNCTIONS == 10
#define FP421_NUMBEROFNONZEROS 84
#endif 

#if NUMBEROFBASISFUNCTIONS == 20
#define FP421_NUMBEROFNONZEROS 340
#endif 

#if NUMBEROFBASISFUNCTIONS == 35
#define FP421_NUMBEROFNONZEROS 1039
#endif 

#if NUMBEROFBASISFUNCTIONS == 56
#define FP421_NUMBEROFNONZEROS 2686
#endif 

#if NUMBEROFBASISFUNCTIONS == 84
#define FP421_NUMBEROFNONZEROS 6069
#endif 

#if NUMBEROFBASISFUNCTIONS == 4
#define FP422_NUMBEROFNONZEROS 11
#endif 

#if NUMBEROFBASISFUNCTIONS == 10
#define FP422_NUMBEROFNONZEROS 61
#endif 

#if NUMBEROFBASISFUNCTIONS == 20
#define FP422_NUMBEROFNONZEROS 232
#endif 

#if NUMBEROFBASISFUNCTIONS == 35
#define FP422_NUMBEROFNONZEROS 684
#endif 

#if NUMBEROFBASISFUNCTIONS == 56
#define FP422_NUMBEROFNONZEROS 1722
#endif 

#if NUMBEROFBASISFUNCTIONS == 84
#define FP422_NUMBEROFNONZEROS 3845
#endif 

#if NUMBEROFBASISFUNCTIONS == 4
#define FP423_NUMBEROFNONZEROS 14
#endif 

#if NUMBEROFBASISFUNCTIONS == 10
#define FP423_NUMBEROFNONZEROS 84
#endif 

#if NUMBEROFBASISFUNCTIONS == 20
#define FP423_NUMBEROFNONZEROS 325
#endif 

#if NUMBEROFBASISFUNCTIONS == 35
#define FP423_NUMBEROFNONZEROS 980
#endif 

#if NUMBEROFBASISFUNCTIONS == 56
#define FP423_NUMBEROFNONZEROS 2509
#endif 

#if NUMBEROFBASISFUNCTIONS == 84
#define FP423_NUMBEROFNONZEROS 5658
#endif 

#if NUMBEROFBASISFUNCTIONS == 4
#define FP431_NUMBEROFNONZEROS 10
#endif 

#if NUMBEROFBASISFUNCTIONS == 10
#define FP431_NUMBEROFNONZEROS 54
#endif 

#if NUMBEROFBASISFUNCTIONS == 20
#define FP431_NUMBEROFNONZEROS 204
#endif 

#if NUMBEROFBASISFUNCTIONS == 35
#define FP431_NUMBEROFNONZEROS 609
#endif 

#if NUMBEROFBASISFUNCTIONS == 56
#define FP431_NUMBEROFNONZEROS 1540
#endif 

#if NUMBEROFBASISFUNCTIONS == 84
#define FP431_NUMBEROFNONZEROS 3444
#endif 

#if NUMBEROFBASISFUNCTIONS == 4
#define FP432_NUMBEROFNONZEROS 15
#endif 

#if NUMBEROFBASISFUNCTIONS == 10
#define FP432_NUMBEROFNONZEROS 93
#endif 

#if NUMBEROFBASISFUNCTIONS == 20
#define FP432_NUMBEROFNONZEROS 371
#endif 

#if NUMBEROFBASISFUNCTIONS == 35
#define FP432_NUMBEROFNONZEROS 1131
#endif 

#if NUMBEROFBASISFUNCTIONS == 56
#define FP432_NUMBEROFNONZEROS 2905
#endif 

#if NUMBEROFBASISFUNCTIONS == 84
#define FP432_NUMBEROFNONZEROS 6556
#endif 

#if NUMBEROFBASISFUNCTIONS == 4
#define FP433_NUMBEROFNONZEROS 15
#endif 

#if NUMBEROFBASISFUNCTIONS == 10
#define FP433_NUMBEROFNONZEROS 93
#endif 

#if NUMBEROFBASISFUNCTIONS == 20
#define FP433_NUMBEROFNONZEROS 371
#endif 

#if NUMBEROFBASISFUNCTIONS == 35
#define FP433_NUMBEROFNONZEROS 1131
#endif 

#if NUMBEROFBASISFUNCTIONS == 56
#define FP433_NUMBEROFNONZEROS 2905
#endif 

#if NUMBEROFBASISFUNCTIONS == 84
#define FP433_NUMBEROFNONZEROS 6556
#endif 

#if NUMBEROFBASISFUNCTIONS == 4
#define FP441_NUMBEROFNONZEROS 12
#endif 

#if NUMBEROFBASISFUNCTIONS == 10
#define FP441_NUMBEROFNONZEROS 68
#endif 

#if NUMBEROFBASISFUNCTIONS == 20
#define FP441_NUMBEROFNONZEROS 258
#endif 

#if NUMBEROFBASISFUNCTIONS == 35
#define FP441_NUMBEROFNONZEROS 773
#endif 

#if NUMBEROFBASISFUNCTIONS == 56
#define FP441_NUMBEROFNONZEROS 1946
#endif 

#if NUMBEROFBASISFUNCTIONS == 84
#define FP441_NUMBEROFNONZEROS 4342
#endif 

#if NUMBEROFBASISFUNCTIONS == 4
#define FP442_NUMBEROFNONZEROS 12
#endif 

#if NUMBEROFBASISFUNCTIONS == 10
#define FP442_NUMBEROFNONZEROS 70
#endif 

#if NUMBEROFBASISFUNCTIONS == 20
#define FP442_NUMBEROFNONZEROS 274
#endif 

#if NUMBEROFBASISFUNCTIONS == 35
#define FP442_NUMBEROFNONZEROS 831
#endif 

#if NUMBEROFBASISFUNCTIONS == 56
#define FP442_NUMBEROFNONZEROS 2120
#endif 

#if NUMBEROFBASISFUNCTIONS == 84
#define FP442_NUMBEROFNONZEROS 4766
#endif 

#if NUMBEROFBASISFUNCTIONS == 4
#define FP443_NUMBEROFNONZEROS 16
#endif 

#if NUMBEROFBASISFUNCTIONS == 10
#define FP443_NUMBEROFNONZEROS 98
#endif 

#if NUMBEROFBASISFUNCTIONS == 20
#define FP443_NUMBEROFNONZEROS 394
#endif 

#if NUMBEROFBASISFUNCTIONS == 35
#define FP443_NUMBEROFNONZEROS 1213
#endif 

#if NUMBEROFBASISFUNCTIONS == 56
#define FP443_NUMBEROFNONZEROS 3124
#endif 

#if NUMBEROFBASISFUNCTIONS == 84
#define FP443_NUMBEROFNONZEROS 7022
#endif 

#if NUMBEROFBASISFUNCTIONS == 4
#define KETADIVMT_NUMBEROFNONZEROS 2
#endif 

#if NUMBEROFBASISFUNCTIONS == 10
#define KETADIVMT_NUMBEROFNONZEROS 17
#endif 

#if NUMBEROFBASISFUNCTIONS == 20
#define KETADIVMT_NUMBEROFNONZEROS 77
#endif 

#if NUMBEROFBASISFUNCTIONS == 35
#define KETADIVMT_NUMBEROFNONZEROS 252
#endif 

#if NUMBEROFBASISFUNCTIONS == 56
#define KETADIVMT_NUMBEROFNONZEROS 672
#endif 

#if NUMBEROFBASISFUNCTIONS == 84
#define KETADIVMT_NUMBEROFNONZEROS 1554
#endif 

#if NUMBEROFBASISFUNCTIONS == 4
#define KETADIVM_NUMBEROFNONZEROS 2
#endif 

#if NUMBEROFBASISFUNCTIONS == 10
#define KETADIVM_NUMBEROFNONZEROS 17
#endif 

#if NUMBEROFBASISFUNCTIONS == 20
#define KETADIVM_NUMBEROFNONZEROS 77
#endif 

#if NUMBEROFBASISFUNCTIONS == 35
#define KETADIVM_NUMBEROFNONZEROS 252
#endif 

#if NUMBEROFBASISFUNCTIONS == 56
#define KETADIVM_NUMBEROFNONZEROS 672
#endif 

#if NUMBEROFBASISFUNCTIONS == 84
#define KETADIVM_NUMBEROFNONZEROS 1554
#endif 

#if NUMBEROFBASISFUNCTIONS == 4
#define KETA_NUMBEROFNONZEROS 2
#endif 

#if NUMBEROFBASISFUNCTIONS == 10
#define KETA_NUMBEROFNONZEROS 17
#endif 

#if NUMBEROFBASISFUNCTIONS == 20
#define KETA_NUMBEROFNONZEROS 77
#endif 

#if NUMBEROFBASISFUNCTIONS == 35
#define KETA_NUMBEROFNONZEROS 252
#endif 

#if NUMBEROFBASISFUNCTIONS == 56
#define KETA_NUMBEROFNONZEROS 672
#endif 

#if NUMBEROFBASISFUNCTIONS == 84
#define KETA_NUMBEROFNONZEROS 1554
#endif 

#if NUMBEROFBASISFUNCTIONS == 4
#define KXIDIVMT_NUMBEROFNONZEROS 1
#endif 

#if NUMBEROFBASISFUNCTIONS == 10
#define KXIDIVMT_NUMBEROFNONZEROS 7
#endif 

#if NUMBEROFBASISFUNCTIONS == 20
#define KXIDIVMT_NUMBEROFNONZEROS 33
#endif 

#if NUMBEROFBASISFUNCTIONS == 35
#define KXIDIVMT_NUMBEROFNONZEROS 108
#endif 

#if NUMBEROFBASISFUNCTIONS == 56
#define KXIDIVMT_NUMBEROFNONZEROS 294
#endif 

#if NUMBEROFBASISFUNCTIONS == 84
#define KXIDIVMT_NUMBEROFNONZEROS 686
#endif 

#if NUMBEROFBASISFUNCTIONS == 4
#define KXIDIVM_NUMBEROFNONZEROS 1
#endif 

#if NUMBEROFBASISFUNCTIONS == 10
#define KXIDIVM_NUMBEROFNONZEROS 7
#endif 

#if NUMBEROFBASISFUNCTIONS == 20
#define KXIDIVM_NUMBEROFNONZEROS 33
#endif 

#if NUMBEROFBASISFUNCTIONS == 35
#define KXIDIVM_NUMBEROFNONZEROS 108
#endif 

#if NUMBEROFBASISFUNCTIONS == 56
#define KXIDIVM_NUMBEROFNONZEROS 294
#endif 

#if NUMBEROFBASISFUNCTIONS == 84
#define KXIDIVM_NUMBEROFNONZEROS 686
#endif 

#if NUMBEROFBASISFUNCTIONS == 4
#define KXI_NUMBEROFNONZEROS 1
#endif 

#if NUMBEROFBASISFUNCTIONS == 10
#define KXI_NUMBEROFNONZEROS 7
#endif 

#if NUMBEROFBASISFUNCTIONS == 20
#define KXI_NUMBEROFNONZEROS 33
#endif 

#if NUMBEROFBASISFUNCTIONS == 35
#define KXI_NUMBEROFNONZEROS 108
#endif 

#if NUMBEROFBASISFUNCTIONS == 56
#define KXI_NUMBEROFNONZEROS 294
#endif 

#if NUMBEROFBASISFUNCTIONS == 84
#define KXI_NUMBEROFNONZEROS 686
#endif 

#if NUMBEROFBASISFUNCTIONS == 4
#define KZETADIVMT_NUMBEROFNONZEROS 3
#endif 

#if NUMBEROFBASISFUNCTIONS == 10
#define KZETADIVMT_NUMBEROFNONZEROS 22
#endif 

#if NUMBEROFBASISFUNCTIONS == 20
#define KZETADIVMT_NUMBEROFNONZEROS 92
#endif 

#if NUMBEROFBASISFUNCTIONS == 35
#define KZETADIVMT_NUMBEROFNONZEROS 287
#endif 

#if NUMBEROFBASISFUNCTIONS == 56
#define KZETADIVMT_NUMBEROFNONZEROS 742
#endif 

#if NUMBEROFBASISFUNCTIONS == 84
#define KZETADIVMT_NUMBEROFNONZEROS 1680
#endif 

#if NUMBEROFBASISFUNCTIONS == 4
#define KZETADIVM_NUMBEROFNONZEROS 3
#endif 

#if NUMBEROFBASISFUNCTIONS == 10
#define KZETADIVM_NUMBEROFNONZEROS 22
#endif 

#if NUMBEROFBASISFUNCTIONS == 20
#define KZETADIVM_NUMBEROFNONZEROS 92
#endif 

#if NUMBEROFBASISFUNCTIONS == 35
#define KZETADIVM_NUMBEROFNONZEROS 287
#endif 

#if NUMBEROFBASISFUNCTIONS == 56
#define KZETADIVM_NUMBEROFNONZEROS 742
#endif 

#if NUMBEROFBASISFUNCTIONS == 84
#define KZETADIVM_NUMBEROFNONZEROS 1680
#endif 

#if NUMBEROFBASISFUNCTIONS == 4
#define KZETA_NUMBEROFNONZEROS 3
#endif 

#if NUMBEROFBASISFUNCTIONS == 10
#define KZETA_NUMBEROFNONZEROS 22
#endif 

#if NUMBEROFBASISFUNCTIONS == 20
#define KZETA_NUMBEROFNONZEROS 92
#endif 

#if NUMBEROFBASISFUNCTIONS == 35
#define KZETA_NUMBEROFNONZEROS 287
#endif 

#if NUMBEROFBASISFUNCTIONS == 56
#define KZETA_NUMBEROFNONZEROS 742
#endif 

#if NUMBEROFBASISFUNCTIONS == 84
#define KZETA_NUMBEROFNONZEROS 1680
#endif 

#if NUMBEROFBASISFUNCTIONS == 4
#define M_NUMBEROFNONZEROS 4
#endif 

#if NUMBEROFBASISFUNCTIONS == 10
#define M_NUMBEROFNONZEROS 10
#endif 

#if NUMBEROFBASISFUNCTIONS == 20
#define M_NUMBEROFNONZEROS 20
#endif 

#if NUMBEROFBASISFUNCTIONS == 35
#define M_NUMBEROFNONZEROS 35
#endif 

#if NUMBEROFBASISFUNCTIONS == 56
#define M_NUMBEROFNONZEROS 56
#endif 

#if NUMBEROFBASISFUNCTIONS == 84
#define M_NUMBEROFNONZEROS 84
#endif 

#if NUMBEROFVARIABLES == 9
#define STARMATRIX_NUMBEROFNONZEROS 24
#endif 

